In [35]:
import pandas as pd

df = pd.read_csv("../data/sensor_data.csv")

df.head()

   time  temperature  vibration    pressure  failure_warning  failure
0     0    70.993428  20.348286   90.097140              0.0      0.0
1     1    69.723471  20.283324   94.725072              0.0      0.0
2     2    71.295377  19.063480   97.064858              0.0      0.0
3     3    73.046060  20.579584  100.748345              0.0      0.0
4     4    69.531693  18.509917  105.120812              0.0      0.0

In [36]:


df.shape

(10000, 6)

In [37]:
# Temperature
df["temp_rolling_mean_20"] = df["temperature"].rolling(window=20).mean()
df["temp_rolling_std_20"] = df["temperature"].rolling(window=20).std()

# Vibration
df["vib_rolling_mean_20"] = df["vibration"].rolling(window=20).mean()
df["vib_rolling_std_20"] = df["vibration"].rolling(window=20).std()

# Pressure
df["pressure_rolling_mean_20"] = df["pressure"].rolling(window=20).mean()
df["pressure_rolling_std_20"] = df["pressure"].rolling(window=20).std()

In [38]:
df.shape

(10000, 12)

In [26]:
df.shape

(9962, 12)

In [39]:
df.isna().sum()

time                         0
temperature                  0
vibration                    0
pressure                     0
failure_warning              0
failure                      0
temp_rolling_mean_20        19
temp_rolling_std_20         19
vib_rolling_mean_20         19
vib_rolling_std_20          19
pressure_rolling_mean_20    19
pressure_rolling_std_20     19
dtype: int64

In [40]:
df = df.dropna().reset_index(drop=True)

In [41]:
df.shape

(9981, 12)

In [42]:
features = [
    "temperature",
    "vibration",
    "pressure",
    "temp_rolling_mean_20",
    "temp_rolling_std_20",
    "vib_rolling_mean_20",
    "vib_rolling_std_20",
    "pressure_rolling_mean_20",
    "pressure_rolling_std_20"
]

X = df[features]
y = df["failure_warning"]

In [43]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X.head()

X shape: (9981, 9)
y shape: (9981,)

,temperature,vibration,pressure,temp_rolling_mean_20,temp_rolling_std_20,vib_rolling_mean_20,vib_rolling_std_20,pressure_rolling_mean_20,pressure_rolling_std_20
0,67.175393,21.820967,97.281535,69.657403,1.920057,19.885067,1.166766,97.469400,5.248320
1,72.931298,22.213278,105.002742,69.754296,2.036398,19.978317,1.275222,98.214680,5.204475
2,69.548447,20.204989,103.715987,69.745545,2.036913,19.974400,1.274356,98.664226,5.275015
3,70.135056,20.148943,98.455193,69.687529,2.006748,20.028673,1.256508,98.733743,5.261973
4,67.150504,19.663680,97.891202,69.392751,1.918506,19.982878,1.252055,98.590886,5.243151

In [44]:
split_index = int(len(X) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

In [45]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (7984, 9)
X_test: (1997, 9)
y_train: (7984,)
y_test: (1997,)

In [48]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\nTrain warnings:")
print(y_train.value_counts())

print("\nTest warnings:")
print(y_test.value_counts())

X_train: (7984, 9)
X_test: (1997, 9)

Train warnings:
failure_warning
0.0    7384
1.0     600
Name: count, dtype: int64

Test warnings:
failure_warning
0.0    1797
1.0     200
Name: count, dtype: int64